### PR TITLE
Custom Error Page

### PR DESCRIPTION
**Pull request by Sarthak0085**
Closes:- #74 

**Description**
I have created a new Page in the PetMe-Frontend pages folder name errorPage and add it to the main.jsx file in which if not any route is find then it goes to that page and in the errorPage i have created one error component in which i have added the custom error page code and i have check it doesn't affect other components.

**Screenshots**
err

### CODE REVIEW

**Comment by Sarthak0085** [comment]
If any changes required in my code please ping me here.

**Comment by pratham-srivastava-07** [comment]
looks good! @Sarthak0085 but make sure this error page does not conflict with the routes like "/report" in which we have rendered an error component declaring that it is being built. Once confirmed, i'll merge it.

For  refrence i am talking about this:
image

**Comment by Sarthak0085** [comment]
@pratham-srivastava-07 actually i have apply changes in that page. As you have mentioned not to conflict. So i will create another component and add the code into that without change the actual <Error /> component.

**Comment by Sarthak0085** [comment]
@pratham-srivastava-07  i have done the changes. You can check and if anything else need ping me. And also check the header component commit #89 pull commit. Apart from that i want to contribute in both backend and frontend component if there anything that i can contribute it will be good. Thanks!

**Comment by pratham-srivastava-07** [comment]
@Sarthak0085 Okay that's what was needed. Merging now!

**Pull request merged**
