### PR TITLE
feature: Card UI Improvement

### LINKED ISSUE #38: Home Page UI Enhancemnet
### Description :spiral_notepad: 
- Need of an UI Component 
- Cards Component to showcase some options
- Under home page 

### Inspiration :framed_picture: 
Screenshot_2024-06-09-23-01-23_1920x1080

### PR DESCRIPTION
**Pull request by Piyush-linux**
Closes #38 

### Description
- Added Card UI
- Showcase our operations

### Screen-Shot :framed_picture: 
Screenshot_2024-06-10-10-18-23_1920x1080

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
Is it responsive @Piyush-linux ?

**Comment by Piyush-linux** [comment]
Im some facing some issue is mobile UI

**Comment by cb7chaitanya** [comment]
What is the issue?

**Comment by Piyush-linux** [comment]
3rd UI card is overlapping with next section

**Comment by cb7chaitanya** [comment]
Try and fix it, then will merge this, UI wise it looks really clean so want to merge it, just fix this

**Comment by Piyush-linux** [comment]
Sure

**Comment by Piyush-linux** [comment]
@cb7chaitanya , Cards have been made Responsive 
Screenshot_2024-06-11-21-58-01_1920x1080

**Comment by cb7chaitanya** [comment]
Great job @Piyush-linux merging it

**Pull request merged**
