### PR TITLE
SOS endpoint done

### PR DESCRIPTION
**Pull request by pratham-srivastava-07**

### CODE REVIEW

**Comment by Tanishq1604** [comment]
@pratham-srivastava-07 u tested it locally right?

**Comment by pratham-srivastava-07** [comment]
yes it's working

**Comment by cb7chaitanya** [comment]
@pratham-srivastava-07 request-response add kardo, what would be the expected response  we get on a successful request and what should be sent when hitting the endpoint

Would add in notion doc

**Comment by pratham-srivastava-07** [comment]
okay

**Pull request merged**
