### PR TITLE
Added signup and login route

### PR DESCRIPTION
**Pull request by Yashgupta9330**
three route made 
1) signup- Used jwt for token generation 
2) otp-used nodemailer for sending otp in mail 
2) login-on successfull login cookie will be sent which contain token data

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
@Yashgupta9330 Will be reviewing it tomorrow

**Comment by Yashgupta9330** [comment]
okk if any changes needed pls tell me i will change it

**Comment by cb7chaitanya** [comment]
Can you give me the req-res for the endpoints, and also 17 files changed, bro?  @Yashgupta9330

**Comment by Yashgupta9330** [comment]
1)  otp route:   http://localhost:3001/auth/otp
{
   "email":"",
}
2) signup route: http://localhost:3001/auth/signup
{
  "first_name": "John",
  "last_name": "Doe",
  "email": "",
  "password": "",
  "address": "123 Main St",
  "city": "Anytown",
  "state": "Anystate",
  "country": "Country",
  "zip_code": "12345",
  "phone_number": "+1234956670",
  "otp":""
}

3) login route:   http://localhost:3001/auth/login

{
    "email":"",
    "password":""
}

**Pull request merged**
