### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by kapilG0**
I tried to update read me based on petme

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
Great work on this but can you just expand the tech stack as the one we are using is quite extensive @kapilG0

**Comment by kapilG0** [comment]
> Great work on this but can you just expand the tech stack as the one we are using is quite extensive @kapilG0

Yes I can add more tech stack please let me know what tech stack will be used . In back-end Nodejs, typescript used in frontend react.js that much info I have and I added these tech stack if there is any other please let me know I will add
Thank you

**Comment by cb7chaitanya** [comment]
The whole repo uses turborepo
Backend uses Node, Express and Typescript
Using Zod for input validation in both Frontend and Backend
React, Tailwind + Javascript in Frontend 
PostgreSQL as the Database and Prisma as the ORM

@kapilG0

**Comment by pratham-srivastava-07** [comment]
any updates on this? @kapilG0

**Pull request merged**
